name: Test and Build
on:
  push:
    branches:
      - netbox-hardware-ingest
  pull_request:
    branches:
      - netbox-hardware-ingest

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: generate coverage report
        run: make cover
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
      - name: Build
        run: make build
